development:
  cloud_name: dm7e2spd5
  api_key: '274849438921466'
  api_secret: "7ow4DF5vyIwU-dJQv80wHaE2CVg"
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dm7e2spd5
  api_key: '274849438921466'
  api_secret: "7ow4DF5vyIwU-dJQv80wHaE2CVg"
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dm7e2spd5
  api_key: '274849438921466'
  api_secret: "7ow4DF5vyIwU-dJQv80wHaE2CVg"
  enhance_image_tag: true
  static_file_support: false