# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.2].define(version: 2024_10_12_115426) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "activity_logs", force: :cascade do |t|
    t.bigint "user_id", null: false
    t.string "action"
    t.string "trackable_type"
    t.integer "trackable_id"
    t.datetime "timestamp"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "name"
    t.index ["user_id"], name: "index_activity_logs_on_user_id"
  end

  create_table "bridges", force: :cascade do |t|
    t.bigint "user_id", null: false
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "slug"
    t.boolean "published", default: false, null: false
    t.string "tip_lucrare_arta"
    t.string "obstacol_traversat"
    t.string "localitatea"
    t.string "categoria"
    t.string "numar_drum"
    t.string "clasa"
    t.string "pozitia_km"
    t.string "an_constructie"
    t.string "schema_statica"
    t.string "structura_rezistenta"
    t.string "mod_executie"
    t.string "oblicitate"
    t.string "culee_fundatie_simplu"
    t.string "culee_fundatie_armat"
    t.string "culee_fundatie_precomprimat"
    t.string "culee_fundatie_metal"
    t.string "culee_fundatie_lemn"
    t.string "culee_fundatie_mixt"
    t.string "culee_elevatie_simplu"
    t.string "culee_elevatie_armat"
    t.string "culee_elevatie_precomprimat"
    t.string "culee_elevatie_metal"
    t.string "culee_elevatie_lemn"
    t.string "culee_elevatie_mixt"
    t.string "pile_fundatie_simplu"
    t.string "pile_fundatie_armat"
    t.string "pile_fundatie_precomprimat"
    t.string "pile_fundatie_metal"
    t.string "pile_fundatie_lemn"
    t.string "pile_fundatie_mixt"
    t.string "pile_elevatie_simplu"
    t.string "pile_elevatie_armat"
    t.string "pile_elevatie_precomprimat"
    t.string "pile_elevatie_metal"
    t.string "pile_elevatie_lemn"
    t.string "pile_elevatie_mixt"
    t.string "structura_rezistenta_simplu"
    t.string "structura_rezistenta_armat"
    t.string "structura_rezistenta_precomprimat"
    t.string "structura_rezistenta_metal"
    t.string "structura_rezistenta_lemn"
    t.string "structura_rezistenta_mixt"
    t.string "lungime"
    t.string "numar_deschideri"
    t.string "lungime_deschidere"
    t.string "latime"
    t.string "aparate_reazem"
    t.string "tip_infrastructurii"
    t.string "tip_fundatii"
    t.string "tip_imbracaminte"
    t.string "rosturi_tip_pozitie"
    t.string "parapeti_pietonali"
    t.string "parapeti_siguranta"
    t.string "racordari_terasamente"
    t.string "aparari_mal"
    t.string "latime_carosabila"
    t.string "latime_trotuar"
    t.string "numar_grinzi"
    t.string "numar_antretoaze"
    t.index ["slug"], name: "index_bridges_on_slug", unique: true
    t.index ["user_id"], name: "index_bridges_on_user_id"
  end

  create_table "flaw_instances", force: :cascade do |t|
    t.bigint "instance_bridge_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "c1_1"
    t.string "c2_1"
    t.string "c4_2"
    t.string "c5_3"
    t.string "c3_4"
    t.string "c3_1_5"
    t.string "c3_2_5"
    t.string "c1_6"
    t.string "c2_6"
    t.string "c1_7"
    t.string "c3_6"
    t.string "c2_7"
    t.string "c3_7"
    t.string "c1_8"
    t.string "c2_8"
    t.string "c3_8"
    t.string "c1_9"
    t.string "c2_9"
    t.string "c3_9"
    t.string "c1_10"
    t.string "c5_11"
    t.string "c1_12"
    t.string "c2_12"
    t.string "c3_12"
    t.string "c5_13"
    t.string "c1_14"
    t.string "c2_14"
    t.string "c3_14"
    t.string "c1_15"
    t.string "c2_15"
    t.string "c1_16"
    t.string "c2_16"
    t.string "c3_16"
    t.string "c1_17"
    t.string "c2_17"
    t.string "c3_17"
    t.string "c1_18"
    t.string "c2_18"
    t.string "c1_19"
    t.string "c5_20"
    t.string "c5_1_21"
    t.string "c5_2_21"
    t.string "c4_1_22"
    t.string "c4_2_22"
    t.string "c4_1_23"
    t.string "c4_2_23"
    t.string "c4_3_23"
    t.string "c5_24"
    t.string "c3_25"
    t.string "c2_26"
    t.string "c1_27"
    t.string "c1_28"
    t.string "c3_1_29"
    t.string "c3_2_29"
    t.string "c3_1_30"
    t.string "c3_2_30"
    t.string "c2_31"
    t.string "c3_31"
    t.string "c1_32"
    t.string "c2_32"
    t.string "c3_1_33"
    t.string "c3_2_33"
    t.string "c1_34"
    t.string "c2_34"
    t.string "c1_35"
    t.string "c2_35"
    t.string "c3_35"
    t.string "c1_36"
    t.string "c2_36"
    t.string "c3_36"
    t.string "c1_1_37"
    t.string "c2_1_37"
    t.string "c1_2_37"
    t.string "c2_2_37"
    t.string "c3_2_37"
    t.string "c1_3_37"
    t.string "c2_3_37"
    t.string "c3_3_37"
    t.string "c1_4_37"
    t.string "c2_4_37"
    t.string "c3_4_37"
    t.string "c1_5_37"
    t.string "c2_5_37"
    t.string "c3_5_37"
    t.string "c1_6_37"
    t.string "c2_6_37"
    t.string "c3_6_37"
    t.string "c1_7_37"
    t.string "c2_7_37"
    t.string "c3_7_37"
    t.string "c1_8_37"
    t.string "c5_38"
    t.string "c1_39"
    t.string "c1_40"
    t.string "c2_40"
    t.string "c1_41"
    t.string "c2_41"
    t.string "c5_42"
    t.string "c3_43"
    t.string "c1_44"
    t.string "c2_44"
    t.string "c3_44"
    t.string "c1_45"
    t.string "c2_45"
    t.string "c5_46"
    t.string "c4_47"
    t.string "c5_48"
    t.string "c1_49"
    t.string "c2_49"
    t.string "c5_50"
    t.string "c5_51"
    t.string "c3_52"
    t.string "c4_53"
    t.string "c1_54"
    t.string "c3_54"
    t.string "c4_1_55"
    t.string "c4_2_55"
    t.string "c4_3_55"
    t.string "c1_56"
    t.string "c1_1_57"
    t.string "c2_1_57"
    t.string "c1_2_57"
    t.string "c2_2_57"
    t.string "c3_58"
    t.string "c3_59"
    t.string "c1_60"
    t.string "c2_60"
    t.string "c4_1_61"
    t.string "c4_2_61"
    t.string "c1_62"
    t.string "c2_62"
    t.string "c5_63"
    t.string "c1_64"
    t.string "c3_64"
    t.string "c5_65"
    t.string "c5_66"
    t.string "c1_67"
    t.string "c2_67"
    t.string "c3_67"
    t.string "c1_68"
    t.string "c2_68"
    t.string "c3_68"
    t.string "c4_69"
    t.string "c1_70"
    t.string "c2_70"
    t.string "c3_70"
    t.string "c1_71"
    t.string "c3_71"
    t.string "c1_72"
    t.string "c3_72"
    t.string "c3_73"
    t.string "c1_74"
    t.string "c2_74"
    t.string "c3_74"
    t.string "c1_75"
    t.string "c1_76"
    t.string "c1_77"
    t.string "c1_78"
    t.string "c1_79"
    t.string "c1_80"
    t.string "c2_81"
    t.string "c2_82"
    t.string "c2_83"
    t.string "c3_84"
    t.string "c3_85"
    t.string "c3_86"
    t.string "c3_87"
    t.string "c3_88"
    t.string "c3_89"
    t.string "c3_90"
    t.string "c5_91"
    t.string "c5_92"
    t.string "c5_93"
    t.string "c5_94"
    t.string "c5_95"
    t.string "c5_96"
    t.string "c5_97"
    t.string "nr_defecte_c1"
    t.string "nr_defecte_c2"
    t.string "nr_defecte_c3"
    t.string "nr_defecte_c4"
    t.string "nr_defecte_c5"
    t.string "depunct_max_di_c1"
    t.string "depunct_max_di_c2"
    t.string "depunct_max_di_c3"
    t.string "depunct_max_di_c4"
    t.string "depunct_max_di_c5"
    t.string "val_indice_c1"
    t.string "val_indice_c2"
    t.string "val_indice_c3"
    t.string "val_indice_c4"
    t.string "val_indice_c5"
    t.string "indice_total_calitate"
    t.string "aprecierea_starii_tehnice"
    t.string "masuri_recomandate"
    t.string "corespunde_ordinul"
    t.string "flaw_instances"
    t.string "f1_depunct"
    t.string "f1"
    t.string "clasa_incarcare"
    t.string "f2"
    t.string "f2_depunct"
    t.string "tipul_suprastructurii"
    t.string "durata_exploatare"
    t.string "f3_depunct"
    t.string "f3"
    t.string "f4_depunct"
    t.string "f4"
    t.string "f5_depunct"
    t.string "f5"
    t.string "ist_c"
    t.string "ist_f"
    t.string "ist_total"
    t.index ["instance_bridge_id"], name: "index_flaw_instances_on_instance_bridge_id"
  end

  create_table "flaws", force: :cascade do |t|
    t.bigint "bridge_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "c1_1"
    t.string "c2_1"
    t.string "c4_2"
    t.string "c5_3"
    t.string "c3_4"
    t.string "c3_1_5"
    t.string "c3_2_5"
    t.string "c1_6"
    t.string "c2_6"
    t.string "c3_6"
    t.string "c1_7"
    t.string "c2_7"
    t.string "c3_7"
    t.string "c1_8"
    t.string "c2_8"
    t.string "c3_8"
    t.string "c1_9"
    t.string "c2_9"
    t.string "c3_9"
    t.string "c1_10"
    t.string "c5_11"
    t.string "c1_12"
    t.string "c2_12"
    t.string "c3_12"
    t.string "c5_13"
    t.string "c1_14"
    t.string "c2_14"
    t.string "c3_14"
    t.string "c1_15"
    t.string "c2_15"
    t.string "c1_16"
    t.string "c2_16"
    t.string "c3_16"
    t.string "c1_17"
    t.string "c2_17"
    t.string "c3_17"
    t.string "c1_18"
    t.string "c2_18"
    t.string "c1_19"
    t.string "c5_20"
    t.string "c5_1_21"
    t.string "c5_2_21"
    t.string "c4_1_22"
    t.string "c4_2_22"
    t.string "c4_1_23"
    t.string "c4_2_23"
    t.string "c4_3_23"
    t.string "c5_24"
    t.string "c3_25"
    t.string "c2_26"
    t.string "c1_27"
    t.string "c1_28"
    t.string "c3_1_29"
    t.string "c3_2_29"
    t.string "c3_1_30"
    t.string "c3_2_30"
    t.string "c2_31"
    t.string "c3_31"
    t.string "c1_32"
    t.string "c2_32"
    t.string "c3_1_33"
    t.string "c3_2_33"
    t.string "c1_34"
    t.string "c2_34"
    t.string "c1_35"
    t.string "c2_35"
    t.string "c3_35"
    t.string "c1_36"
    t.string "c2_36"
    t.string "c3_36"
    t.string "c1_1_37"
    t.string "c2_1_37"
    t.string "c1_2_37"
    t.string "c2_2_37"
    t.string "c3_2_37"
    t.string "c1_3_37"
    t.string "c2_3_37"
    t.string "c3_3_37"
    t.string "c1_4_37"
    t.string "c2_4_37"
    t.string "c3_4_37"
    t.string "c1_5_37"
    t.string "c2_5_37"
    t.string "c3_5_37"
    t.string "c1_6_37"
    t.string "c2_6_37"
    t.string "c3_6_37"
    t.string "c1_7_37"
    t.string "c2_7_37"
    t.string "c3_7_37"
    t.string "c1_8_37"
    t.string "c1_9_37"
    t.string "c5_38"
    t.string "c1_39"
    t.string "c1_40"
    t.string "c2_40"
    t.string "c1_41"
    t.string "c2_41"
    t.string "c5_42"
    t.string "c3_43"
    t.string "c1_44"
    t.string "c2_44"
    t.string "c3_44"
    t.string "c1_45"
    t.string "c2_45"
    t.string "c5_46"
    t.string "c4_47"
    t.string "c5_48"
    t.string "c1_49"
    t.string "c2_49"
    t.string "c5_50"
    t.string "c3_52"
    t.string "c4_53"
    t.string "c1_54"
    t.string "c3_54"
    t.string "c4_1_55"
    t.string "c4_2_55"
    t.string "c4_3_55"
    t.string "c1_56"
    t.string "c1_1_57"
    t.string "c2_1_57"
    t.string "c1_2_57"
    t.string "c2_2_57"
    t.string "c3_58"
    t.string "c3_59"
    t.string "c1_60"
    t.string "c2_60"
    t.string "c4_1_61"
    t.string "c4_2_61"
    t.string "c1_62"
    t.string "c2_62"
    t.string "c5_63"
    t.string "c1_64"
    t.string "c3_64"
    t.string "c5_65"
    t.string "c5_66"
    t.string "c1_67"
    t.string "c2_67"
    t.string "c3_67"
    t.string "c1_68"
    t.string "c2_68"
    t.string "c3_68"
    t.string "c4_69"
    t.string "c1_70"
    t.string "c2_70"
    t.string "c3_70"
    t.string "c1_71"
    t.string "c3_71"
    t.string "c1_72"
    t.string "c3_72"
    t.string "c3_73"
    t.string "c1_74"
    t.string "c2_74"
    t.string "c3_74"
    t.string "c1_75"
    t.string "c1_76"
    t.string "c1_77"
    t.string "c1_78"
    t.string "c1_79"
    t.string "c1_80"
    t.string "c2_81"
    t.string "c2_82"
    t.string "c2_83"
    t.string "c3_84"
    t.string "c3_85"
    t.string "c3_86"
    t.string "c3_87"
    t.string "c3_88"
    t.string "c3_89"
    t.string "c3_90"
    t.string "c5_91"
    t.string "c5_92"
    t.string "c5_93"
    t.string "c5_94"
    t.string "c5_95"
    t.string "c5_96"
    t.string "c5_97"
    t.string "c5_51"
    t.string "nr_defecte_c1"
    t.string "nr_defecte_c2"
    t.string "nr_defecte_c3"
    t.string "nr_defecte_c4"
    t.string "nr_defecte_c5"
    t.string "depunct_max_di_c1"
    t.string "depunct_max_di_c2"
    t.string "depunct_max_di_c3"
    t.string "depunct_max_di_c4"
    t.string "depunct_max_di_c5"
    t.string "val_indice_c1"
    t.string "val_indice_c2"
    t.string "val_indice_c3"
    t.string "val_indice_c4"
    t.string "val_indice_c5"
    t.string "indice_total_calitate"
    t.string "corespunde_ordinul"
    t.string "f1_depunct"
    t.string "f1"
    t.string "clasa_incarcare"
    t.string "f2"
    t.string "f2_depunct"
    t.string "tipul_suprastructurii"
    t.string "durata_exploatare"
    t.string "f3_depunct"
    t.string "f3"
    t.string "f4_depunct"
    t.string "f4"
    t.string "f5_depunct"
    t.string "f5"
    t.string "ist_c"
    t.string "ist_f"
    t.string "ist_total"
    t.string "aprecierea_starii_tehnice"
    t.string "masuri_recomandate"
    t.string "suma_c1"
    t.string "suma_f1"
    t.string "suma_ist"
    t.index ["bridge_id"], name: "index_flaws_on_bridge_id"
  end

  create_table "instance_bridges", force: :cascade do |t|
    t.bigint "bridge_id", null: false
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "tip_lucrare_arta"
    t.string "obstacol_traversat"
    t.string "localitatea"
    t.string "categoria"
    t.string "numar_drum"
    t.string "clasa"
    t.string "pozitia_km"
    t.string "an_constructie"
    t.string "schema_statica"
    t.string "structura_rezistenta"
    t.string "mod_executie"
    t.string "oblicitate"
    t.string "culee_fundatie_simplu"
    t.string "culee_fundatie_armat"
    t.string "culee_fundatie_precomprimat"
    t.string "culee_fundatie_metal"
    t.string "culee_fundatie_lemn"
    t.string "culee_fundatie_mixt"
    t.string "culee_elevatie_simplu"
    t.string "culee_elevatie_armat"
    t.string "culee_elevatie_precomprimat"
    t.string "culee_elevatie_metal"
    t.string "culee_elevatie_lemn"
    t.string "culee_elevatie_mixt"
    t.string "pile_fundatie_simplu"
    t.string "pile_fundatie_armat"
    t.string "pile_fundatie_precomprimat"
    t.string "pile_fundatie_metal"
    t.string "pile_fundatie_lemn"
    t.string "pile_fundatie_mixt"
    t.string "pile_elevatie_simplu"
    t.string "pile_elevatie_armat"
    t.string "pile_elevatie_precomprimat"
    t.string "pile_elevatie_metal"
    t.string "pile_elevatie_lemn"
    t.string "pile_elevatie_mixt"
    t.string "structura_rezistenta_simplu"
    t.string "structura_rezistenta_armat"
    t.string "structura_rezistenta_precomprimat"
    t.string "structura_rezistenta_metal"
    t.string "structura_rezistenta_lemn"
    t.string "structura_rezistenta_mixt"
    t.string "lungime"
    t.string "numar_deschideri"
    t.string "lungime_deschidere"
    t.string "latime"
    t.string "latime_carosabila"
    t.string "latime_trotuar"
    t.string "numar_grinzi"
    t.string "numar_antretoaze"
    t.string "aparate_reazem"
    t.string "tip_infrastructurii"
    t.string "tip_fundatii"
    t.string "tip_imbracaminte"
    t.string "rosturi_tip_pozitie"
    t.string "parapeti_pietonali"
    t.string "parapeti_siguranta"
    t.string "racordari_terasamente"
    t.string "aparari_mal"
    t.index ["bridge_id"], name: "index_instance_bridges_on_bridge_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "firstname"
    t.string "lastname"
    t.string "username"
    t.string "role", default: "student"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
    t.index ["username"], name: "index_users_on_username", unique: true
  end

  add_foreign_key "activity_logs", "users"
  add_foreign_key "bridges", "users"
  add_foreign_key "flaw_instances", "instance_bridges"
  add_foreign_key "flaws", "bridges"
  add_foreign_key "instance_bridges", "bridges"
end
