class AddFieldsToFlaw < ActiveRecord::Migration[7.2]
  def change
    add_column :flaws, :c2_1, :string
    add_column :flaws, :c1_1, :string
    add_column :flaws, :c4_2, :string
    add_column :flaws, :c5_3, :string
    add_column :flaws, :c3_4, :string
    add_column :flaws, :c3_1_5, :string
    add_column :flaws, :c3_2_5, :string
    add_column :flaws, :c1_6, :string
    add_column :flaws, :c2_6, :string
    add_column :flaws, :c1_7, :string
    add_column :flaws, :c3_6, :string
    add_column :flaws, :c2_7, :string
    add_column :flaws, :c3_7, :string
    add_column :flaws, :c1_8, :string
    add_column :flaws, :c2_8, :string
    add_column :flaws, :c3_8, :string
    add_column :flaws, :c1_9, :string
    add_column :flaws, :c2_9, :string
    add_column :flaws, :c3_9, :string
    add_column :flaws, :c1_10, :string
    add_column :flaws, :c5_11, :string
    add_column :flaws, :c1_12, :string
    add_column :flaws, :c2_12, :string
    add_column :flaws, :c3_12, :string
    add_column :flaws, :c5_13, :string
    add_column :flaws, :c1_14, :string
    add_column :flaws, :c2_14, :string
    add_column :flaws, :c3_14, :string
    add_column :flaws, :c1_15, :string
    add_column :flaws, :c2_15, :string
    add_column :flaws, :c1_16, :string
    add_column :flaws, :c2_16, :string
    add_column :flaws, :c3_16, :string
    add_column :flaws, :c1_17, :string
    add_column :flaws, :c2_17, :string
    add_column :flaws, :c3_17, :string
    add_column :flaws, :c1_18, :string
    add_column :flaws, :c2_18, :string
    add_column :flaws, :c1_19, :string
    add_column :flaws, :c5_20, :string
    add_column :flaws, :c5_1_21, :string
    add_column :flaws, :c5_2_21, :string
    add_column :flaws, :c4_1_22, :string
    add_column :flaws, :c4_2_22, :string
    add_column :flaws, :c4_1_23, :string
    add_column :flaws, :c4_2_23, :string
    add_column :flaws, :c4_3_23, :string
    add_column :flaws, :c5_24, :string
    add_column :flaws, :c3_25, :string
    add_column :flaws, :c2_26, :string
    add_column :flaws, :c1_27, :string
    add_column :flaws, :c1_28, :string
    add_column :flaws, :c3_1_29, :string
    add_column :flaws, :c3_2_29, :string
    add_column :flaws, :c3_1_30, :string
    add_column :flaws, :c3_2_30, :string
    add_column :flaws, :c2_31, :string
    add_column :flaws, :c3_31, :string
    add_column :flaws, :c1_32, :string
    add_column :flaws, :c2_32, :string
    add_column :flaws, :c3_1_33, :string
    add_column :flaws, :c3_2_33, :string
    add_column :flaws, :c1_34, :string
    add_column :flaws, :c2_34, :string
    add_column :flaws, :c1_35, :string
    add_column :flaws, :c2_35, :string
    add_column :flaws, :c3_35, :string
    add_column :flaws, :c1_36, :string
    add_column :flaws, :c2_36, :string
    add_column :flaws, :c3_36, :string
    add_column :flaws, :c1_1_37, :string
    add_column :flaws, :c2_1_37, :string
    add_column :flaws, :c1_2_37, :string
    add_column :flaws, :c2_2_37, :string
    add_column :flaws, :c3_2_37, :string

    add_column :flaws, :c1_3_37, :string
    add_column :flaws, :c2_3_37, :string
    add_column :flaws, :c3_3_37, :string

    add_column :flaws, :c1_4_37, :string
    add_column :flaws, :c2_4_37, :string
    add_column :flaws, :c3_4_37, :string

    add_column :flaws, :c1_5_37, :string
    add_column :flaws, :c2_5_37, :string
    add_column :flaws, :c3_5_37, :string

    add_column :flaws, :c1_6_37, :string
    add_column :flaws, :c2_6_37, :string
    add_column :flaws, :c3_6_37, :string

    add_column :flaws, :c1_7_37, :string
    add_column :flaws, :c2_7_37, :string
    add_column :flaws, :c3_7_37, :string

    add_column :flaws, :c1_8_37, :string
    add_column :flaws, :c1_9_37, :string

    add_column :flaws, :c5_38, :string
    add_column :flaws, :c1_39, :string
    add_column :flaws, :c1_40, :string
    add_column :flaws, :c2_40, :string
    add_column :flaws, :c1_41, :string
    add_column :flaws, :c2_41, :string
    add_column :flaws, :c5_42, :string
    add_column :flaws, :c3_43, :string
    add_column :flaws, :c1_44, :string
    add_column :flaws, :c2_44, :string
    add_column :flaws, :c3_44, :string
    add_column :flaws, :c1_45, :string
    add_column :flaws, :c2_45, :string
    add_column :flaws, :c5_46, :string
    add_column :flaws, :c4_47, :string
    add_column :flaws, :c5_48, :string
    add_column :flaws, :c1_49, :string
    add_column :flaws, :c2_49, :string
    add_column :flaws, :c5_50, :string
    add_column :flaws, :c3_52, :string
    add_column :flaws, :c4_53, :string
    add_column :flaws, :c1_54, :string
    add_column :flaws, :c3_54, :string
    add_column :flaws, :c4_1_55, :string
    add_column :flaws, :c4_2_55, :string
    add_column :flaws, :c4_3_55, :string
    add_column :flaws, :c1_56, :string
    add_column :flaws, :c1_1_57, :string
    add_column :flaws, :c2_1_57, :string
    add_column :flaws, :c1_2_57, :string
    add_column :flaws, :c2_2_57, :string
    add_column :flaws, :c3_58, :string
    add_column :flaws, :c3_59, :string
    add_column :flaws, :c1_60, :string
    add_column :flaws, :c2_60, :string
    add_column :flaws, :c4_1_61, :string
    add_column :flaws, :c4_2_61, :string
    add_column :flaws, :c1_62, :string
    add_column :flaws, :c2_62, :string
    add_column :flaws, :c5_63, :string
    add_column :flaws, :c1_64, :string
    add_column :flaws, :c3_64, :string
    add_column :flaws, :c5_65, :string
    add_column :flaws, :c5_66, :string
    add_column :flaws, :c1_67, :string
    add_column :flaws, :c2_67, :string
    add_column :flaws, :c3_67, :string
    add_column :flaws, :c1_68, :string
    add_column :flaws, :c2_68, :string
    add_column :flaws, :c3_68, :string
    add_column :flaws, :c4_69, :string
    add_column :flaws, :c1_70, :string
    add_column :flaws, :c2_70, :string
    add_column :flaws, :c3_70, :string
    add_column :flaws, :c1_71, :string
    add_column :flaws, :c3_71, :string
    add_column :flaws, :c1_72, :string
    add_column :flaws, :c3_72, :string
    add_column :flaws, :c3_73, :string
    add_column :flaws, :c1_74, :string
    add_column :flaws, :c2_74, :string
    add_column :flaws, :c3_74, :string
    add_column :flaws, :c1_75, :string
    add_column :flaws, :c1_76, :string
    add_column :flaws, :c1_77, :string
    add_column :flaws, :c1_78, :string
    add_column :flaws, :c1_79, :string
    add_column :flaws, :c1_80, :string
    add_column :flaws, :c2_81, :string
    add_column :flaws, :c2_82, :string
    add_column :flaws, :c2_83, :string
    add_column :flaws, :c3_84, :string
    add_column :flaws, :c3_85, :string
    add_column :flaws, :c3_86, :string
    add_column :flaws, :c3_87, :string
    add_column :flaws, :c3_88, :string
    add_column :flaws, :c3_89, :string
    add_column :flaws, :c3_90, :string
    add_column :flaws, :c5_91, :string
    add_column :flaws, :c5_92, :string
    add_column :flaws, :c5_93, :string
    add_column :flaws, :c5_94, :string
    add_column :flaws, :c5_95, :string
    add_column :flaws, :c5_96, :string
    add_column :flaws, :c5_97, :string
  end
end
